# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: All About Me - David Choy
email: davidchoy98@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  David Choy, a Software Engineering graduates (batch May 2020) from UTAR Sg. Long Campus. 
  This is a site for me to place all my memories during the school days, as well as a place for me to record my journey of being a Developer / Software Engineer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://davidchoy98.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  davidchoy98

# Build settings
markdown: kramdown
scss:
  scss_dir : assets/scss
permalink: pretty
plugins:
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
