# Site settings
title: All about me - David Choy
email: davidchoy98@gmail.com
description: >-
  David Choy,  a fresh graduates (batch May 2020) from UTAR Sg. Long Campus. 
  This is a site for me to place all my memories during the school days.
baseurl: ""
url: "https://davidchoy98.github.io"
github_username: davidchoy98

# Build settings
markdown: kramdown
scss:
  scss_dir : assets/scss
permalink: pretty
plugins:
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
